version: 0.0.{build}
image:
  - Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

install:
  - ps: .\build.ps1 -Target Setup

build_script:
  - ps: .\build.ps1 -Target Build

after_build:
  - ps: .\build.ps1 -Target Package

test_script:
  - ps: .\build.ps1 -Target UnitTests
  - ps: .\build.ps1 -Target IntegrationTests

after_test:
  # Upload coverage report to codecov
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f .testresults/unit-tests.xml
      bash codecov.sh -f .testresults/integration-tests.xml

artifacts:
  - path: .packaging\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: n2Eh0aqFAvZpxlFKUys0CBMzRxc8FpPzuElVn65T8rqX2RowroyDK4xxPzLdOE+1
  artifact: /.*\.nupkg/

environment:
  nuget_key:
    secure: n2Eh0aqFAvZpxlFKUys0CBMzRxc8FpPzuElVn65T8rqX2RowroyDK4xxPzLdOE+1
